#- name: Install redis rpm
#  ansible.builtin.yum:
#    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
#    state: installed
#    disable_gpg_check: true

#- name: Enable Redis 7
#  ansible.builtin.shell: dnf module disable redis -y ; dnf module enable redis:7 -y

- name: Install redis
  ansible.builtin.dnf:
    name: redis
    state: installed   #installed - latest


#- name: Update listen address /etc/redis.conf
#  ansible.builtin.replace:
#    path: /etc/redis.conf
#    regexp: '127.0.0.1'
#    replace: '0.0.0.0'
#
#- name: Update listen address /etc/redis/redis.conf
#  ansible.builtin.replace:
#    path: /etc/redis/redis.conf
#    regexp: '127.0.0.1'
#    replace: '0.0.0.0'
- name: Update Redis Config - Listen Address
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Update Redis Config - Protected Mode
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: 'protected-mode yes'
    replace: 'protected-mode no'

- name: systemd service
  ansible.builtin.systemd:
    name: redis
    state: restarted
    enabled: yes