

- name: Adding app user roboshop
  ansible.builtin.user:
    name: roboshop
- name: removing app directory
  ansible.builtin.file:
    path: /app
    state: absent
- name: creating app directory
  ansible.builtin.file:
    path: /app
    state: directory
- name: Unarchive  app content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{component}}.zip
    dest: /app
    remote_src: yes
