- name: frontend setup
  hosts: all
  become: true
  tasks:
    - name: Installing Nginx
      ansible.builtin.yum:
        - name: nginx
          state: latest
    - name: copy
      ansible.builtin.copy:
        src: nginx-roboshop.conf
        dest: /etc/nginx/default.d/roboshop.conf
    - name:  remove directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: absent
    - name: create a directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: directory
    - name: Download and extract Application content
      ansible.builtin.unarchive:
        src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
        dest: /usr/share/nginx/html
        remote_src: yes
    - name: Restart and enable nginx service
      ansible.builtin.systemd:
        - name: nginx
          state: restarted
          enabled: yes